name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build Docker image
        run: docker build -t docker.io/sahildahake/wisecow-image:latest .
      
      - name: Push Docker image to registry
        run: docker push docker.io/sahildahake/wisecow-image:latest
      
      - name: Update Kubernetes deployment
        uses: appleboy/kubectl-action@master
        with:
          k8s_kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}
          command: apply
          args: -f deployment.yaml -f service.yaml
